import { AnalyzerIssue } from '@auditpilot/analyzers';

import { GeneratedTestFile } from './types.js';

export function generateTestForIssue(issue: AnalyzerIssue): GeneratedTestFile {
  const fileName = `${slugify(issue.title)}.spec.ts`;
  const targetUrl = issue.affectedUrl ?? issue.affectedEndpoint ?? 'https://example.com';

  const content = buildTestContent(issue, targetUrl);

  return { fileName, content };
}

export function generateTestSuite(issues: AnalyzerIssue[]): GeneratedTestFile[] {
  const seenFileNames = new Set<string>();
  const files: GeneratedTestFile[] = [];

  for (const issue of issues) {
    const file = generateTestForIssue(issue);
    if (seenFileNames.has(file.fileName)) {
      continue;
    }
    seenFileNames.add(file.fileName);
    files.push(file);
  }

  return files;
}

function buildTestContent(issue: AnalyzerIssue, targetUrl: string): string {
  const header = `import { test, expect } from '@playwright/test';\n\n// Regression test generated by AuditPilot AI for:\n// "${issue.title}" (${issue.category}/${issue.severity})\n`;

  switch (issue.category) {
    case 'SECURITY':
    case 'SERVER_CONFIG':
      return `${header}
test('${escapeTitle(issue.title)}', async ({ request }) => {
  const response = await request.get('${targetUrl}');
  const headers = response.headers();

  expect(response.status(), 'response should not be a server error').toBeLessThan(500);
  expect(Object.keys(headers).length, 'response should include security headers').toBeGreaterThan(0);
});
`;

    case 'BACKEND_API':
    case 'NETWORK':
      return `${header}
test('${escapeTitle(issue.title)}', async ({ request }) => {
  const response = await request.get('${targetUrl}');

  expect(response.status(), 'endpoint should not return a server error').toBeLessThan(500);
});
`;

    case 'PERFORMANCE':
      return `${header}
test('${escapeTitle(issue.title)}', async ({ page }) => {
  const startedAt = Date.now();
  await page.goto('${targetUrl}');
  const loadTimeMs = Date.now() - startedAt;

  expect(loadTimeMs, 'page should load within the performance budget').toBeLessThan(3000);
});
`;

    case 'ACCESSIBILITY':
      return `${header}
test('${escapeTitle(issue.title)}', async ({ page }) => {
  await page.goto('${targetUrl}');

  const imagesWithoutAlt = await page.$$eval('img:not([alt])', (images) => images.length);
  expect(imagesWithoutAlt, 'all images should have an alt attribute').toBe(0);
});
`;

    case 'FRONTEND':
      return `${header}
test('${escapeTitle(issue.title)}', async ({ page }) => {
  const consoleErrors: string[] = [];
  page.on('console', (message) => {
    if (message.type() === 'error') {
      consoleErrors.push(message.text());
    }
  });

  await page.goto('${targetUrl}');

  expect(consoleErrors, 'page should not log console errors').toEqual([]);
});
`;

    default:
      return `${header}
test('${escapeTitle(issue.title)}', async ({ page }) => {
  const response = await page.goto('${targetUrl}');

  expect(response?.ok(), 'page should load successfully').toBeTruthy();
});
`;
  }
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
    .slice(0, 60) || 'generated-test';
}

function escapeTitle(value: string): string {
  return value.replace(/'/g, "\\'");
}
